# Generated by Django 2.0.5 on 2018-06-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='eemail',
            field=models.EmailField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
