# Generated by Django 2.0.5 on 2018-06-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_eemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='eemail',
            field=models.EmailField(max_length=254),
        ),
    ]
